### ISSUE TITLE
[Feature Request] Add append & prepend options

### ISSUE THREAD

**Issue by vanessayuenn** [github/quote-selection#19]
Hi! We would like to make the quote insertion more customizable by adding options to append and prepend strings to the quotes. I imagine the usage can look something like this:
```
quote(selection.toString(), selection.getRangeAt(0), {
  prepend: 'before quote', 
  append: 'after quote' 
})
```
which would insert the following text to the textarea:
```
before quote

> intelligent thing that was quoted

after quote
```

For [our use case](https://github.com/github/ce-oss-happiness/issues/74), we only need these additional options for the `quote` function, but perhaps it will make sense to also allow these options to be set at `install`?

To set expectations, our team would be happy to take on the work to actually build out this feature, but we'd like to first get your 👍 on the approach and direction!

**Comment by muan** [comment]
It seems like this can potentially complicate the behavior code quite a bit, considering that there is already an event exposed to allow for quote content customization (https://github.com/github/quote-selection#events). I understand the desire is to inject content that _isn't_ quoted with `>`. But then that sounds like it could be out of the scope of `quote-selection`.

I look at the code referenced in your issue, and I think this can already be achieved without modifying the code in `quote-selection` as the module has exported the functions needed for you to interact with the target textarea. Would you mind trying something like this?

```js
import {getContainer, getTextarea, quote} from '@github/quote-selection'

on('click', '.js-quote-button', function(event) {
  const textarea = getTextarea(getContainer(event.target))
  textarea.value += 'before quote\n\n'
  quote(selection, range)
  textarea.value += '\n\nafter quote'
})
```

I hope this would unblock you first. Lmk.

**Comment by vanessayuenn** [comment]
@muan you are so right! I haven't tried it yet, but I think your suggestion could totally work and is a lot simpler! Thank you for that, and my bad for over-complicating things 🙈. I will close this for now.
